<?php

class baru
{
    public function tes()
    {
        $this->validate([
            'f17_1' => 'required',
            'f17_2b' => 'required',
            'f17_3' => 'required',
            'f17_4b' => 'required',
            'f17_5' => 'required',
            'f17_6b' => 'required',
            'f17_5a' => 'required',
            'f17_6ba' => 'required',
            'f17_7' => 'required',
            'f17_8b' => 'required',
            'f17_9' => 'required',
            'f17_10b' => 'required',
            'f17_11' => 'required',
            'f17_12b' => 'required',
            'f17_13' => 'required',
            'f17_14b' => 'required',
            'f17_15' => 'required',
            'f17_16b' => 'required',
            'f17_17' => 'required',
            'f17_18b' => 'required',
            'f17_19' => 'required',
            'f17_20b' => 'required',
            'f17_21' => 'required',
            'f17_22b' => 'required',
            'f17_23' => 'required',
            'f17_24b' => 'required',
            'f17_25' => 'required',
            'f17_26b' => 'required',
            'f17_27' => 'required',
            'f17_28b' => 'required',
            'f17_29' => 'required',
            'f17_30b' => 'required',
            'f17_31' => 'required',
            'f17_32b' => 'required',
            'f17_33' => 'required',
            'f17_34b' => 'required',
            'f17_35' => 'required',
            'f17_37' => 'required',
            'f17_38b' => 'required',
            'f17_37a' => 'required',
            'f17_38ba' => 'required',
            'f17_39' => 'required',
            'f17_40b' => 'required',
            'f17_41' => 'required',
            'f17_42b' => 'required',
            'f17_43' => 'required',
            'f17_44b' => 'required',
            'f17_46b' => 'required',
            'f17_47' => 'required',
            'f17_48b' => 'required',
            'f17_49' => 'required',
            'f17_50b' => 'required',
            'f17_51' => 'required',
            'f17_52b' => 'required',
            'f17_53' => 'required',
            'f17_54b' => 'required',
        ]);
    }
}
